# Generated by Django 4.2.19 on 2026-02-11 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
