# Generated by Django 4.2.19 on 2026-02-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_alter_release_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='user_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
